[features]
seeds = false
[programs.localnet]
messages="BMkLrsFDEUtW46wgiXhES7pTiRGpfSF5b7FsCbYCq4qo"
counter="4HozAEDcAaTGxV9KZx34gxHAEAPsFJNaoqqgupHTUnT7"

[programs.devnet]
counter="4HozAEDcAaTGxV9KZx34gxHAEAPsFJNaoqqgupHTUnT7"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/mahesh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
